branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "@semantic-release/git"

# Configuration for the commit analyzer
commit-analyzer:
  preset: conventionalcommits
  releaseRules:
    - type: feat
      release: minor
    - type: fix
      release: patch
    - type: perf
      release: patch
    - type: docs
      scope: README
      release: patch
    - type: chore
      release: patch
    - scope: no-release
      release: patch

changelog:
    - changelogFile: "CHANGELOG.md"
      changelogTitle: "# 🚦 CHANGELOG"

# Configuration for the Git plugin
git:
  assets:
    - CHANGELOG.md
  message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

github:
  - assets:
    - path: "CHANGELOG.md"
      label: "Changelog"
