name: Build and Tag

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: login
          run: |
            echo "${{secrets.GITHUB_TOKEN}}" | docker login -u ${{github.action}} --password-stdin ghcr.io/${{github.repository_owner}}
        - name: build
          run: |
            docker build -t ghcr.io/${{github.repository}}:latest . 
            docker push ghcr.io/${{github.repository}}:latest
            docker tag ghcr.io/${{github.repository}}:latest ghcr.io/${{github.repository}}:${{github.ref_name}}
            docker push ghcr.io/${{github.repository}}:${{github.ref_name}}
