---
name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip' # caching pip dependencies
      - name: Python Semantic Release
        id: release
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m pip install python-semantic-release
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release version --no-push --skip-build
