---
name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    # NOTE: this enables trusted publishing.
    # See https://github.com/pypa/gh-action-pypi-publish/tree/release/v1#trusted-publishing
    # and https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
